<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<PackAsTool>true</PackAsTool>
		<ToolCommandName>arch</ToolCommandName>
		<PackageId>Architectore.CleanArchitecture</PackageId>
		<Version>1.1.0</Version>
		<Authors>Mario Soto Moreno</Authors>
	</PropertyGroup>

	<ItemGroup>
		<Folder Include="Templates\Implementations\" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="EssentialLayers" Version="1.7.2" />
	  <PackageReference Include="System.CommandLine" Version="2.0.0-beta4.22272.1" />
	</ItemGroup>

	<ItemGroup>
	  <None Update="Templates\Contracts\GetAll.txt">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="Templates\Contracts\GetById.txt">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="Templates\Contracts\New.txt">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="Templates\Contracts\Update.txt">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="Templates\Implementations\Delete.txt">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="Templates\Implementations\GetAll.txt">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="Templates\Implementations\GetById.txt">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="Templates\Implementations\New.txt">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="Templates\Implementations\Update.txt">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="Templates\Queries\IQuery.txt">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="Templates\Queries\Query.txt">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="Templates\Repositories\IRepository.txt">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="Templates\Repositories\Repository.txt">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="Templates\Services\IServices.txt">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="Templates\Services\Services.txt">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	</ItemGroup>

</Project>
